services:
  pg:
    image: bitnami/postgresql:13.16.0
    container_name: inorbit-server

    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit